# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Laboratory's name")),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_title', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntakeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('date_laboratory', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.CharField(max_length=200)),
                ('smell_20_celsium', models.CharField(blank=True, max_length=200, null=True)),
                ('smell_60_celsium', models.CharField(blank=True, max_length=200, null=True)),
                ('aftertaste', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('dry_residue', models.CharField(blank=True, max_length=200, null=True)),
                ('pH', models.CharField(blank=True, max_length=200, null=True)),
                ('rigidity', models.CharField(blank=True, max_length=200, null=True)),
                ('nitrates', models.CharField(blank=True, max_length=200, null=True)),
                ('chlorides', models.CharField(blank=True, max_length=200, null=True)),
                ('sulphates', models.CharField(blank=True, max_length=200, null=True)),
                ('iron_overall', models.CharField(blank=True, max_length=200, null=True)),
                ('manganese', models.CharField(blank=True, max_length=200, null=True)),
                ('fluorine', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntakePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_on_map', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='waterintakeinfo',
            name='intake_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersamples.WaterIntakePoint'),
        ),
        migrations.AddField(
            model_name='waterintakeinfo',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersamples.Laboratory'),
        ),
        migrations.AddField(
            model_name='waterintakeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
