# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersamples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintakeinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Знятий'), (1, 'Досліджений')], default=0),
            preserve_default=False,
        ),
    ]
