# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 21:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersamples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='date_laboratory',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='date_taken',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='dry_residue',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='fluorine',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='iron_overall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='manganese',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='nitrates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='pH',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='rigidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='sulphates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
