# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:25
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watersamples', '0002_waterintakeinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintakepoint',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterintakepoint',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
