# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 21:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersamples', '0002_auto_20170501_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='aftertaste',
            field=models.IntegerField(blank=True, choices=[(0, '0 - Not found'), (1, '1 - Detected by taster'), (2, '2 - Detected by consumer'), (3, '3 - Easily detected'), (4, '4 - Strong smell and taste'), (5, '5 - Undrinkable')], null=True, verbose_name='Aftertaste (points)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chlorides (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='color',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Color (degrees)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='dry_residue',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dry residue (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='fluorine',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fluorine (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='iron_overall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iron (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='manganese',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manganese (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='nitrates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nitrates (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='pH',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potential of hydrogen (PH)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='rigidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hardness (mg-eq/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='smell_20_celsium',
            field=models.IntegerField(blank=True, choices=[(0, '0 - Not found'), (1, '1 - Detected by taster'), (2, '2 - Detected by consumer'), (3, '3 - Easily detected'), (4, '4 - Strong smell and taste'), (5, '5 - Undrinkable')], null=True, verbose_name='Smell 20 celsium (points)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='smell_60_celsium',
            field=models.IntegerField(blank=True, choices=[(0, '0 - Not found'), (1, '1 - Detected by taster'), (2, '2 - Detected by consumer'), (3, '3 - Easily detected'), (4, '4 - Strong smell and taste'), (5, '5 - Undrinkable')], null=True, verbose_name='Smell 60 celsium (points)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='sulphates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sulphates (mg/dm3)'),
        ),
        migrations.AlterField(
            model_name='waterintakeinfo',
            name='temperature',
            field=models.IntegerField(verbose_name='Temperature (points)'),
        ),
    ]
