# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersamples', '0003_auto_20170406_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterintakepoint',
            old_name='market_on_map',
            new_name='name',
        ),
    ]
